{
    'name': 'Shipstation Connector',
    'version': '12.0.24',
    'author': "Vraja Technologies",
    'price': 249,
    'currency': 'EUR',
    'license': 'AGPL-3',
    'category':"Website",
    'summary':"Shipstation connector provide the functionality of export Orders, Lable Process, Rate and Import Order Process according to the store.",
    'depends': ['delivery','sale'],
    'data': [
	     'security/ir.model.access.csv',
             'view/shipstation_odoo_integration_config.xml',
             'view/shipstation_store_view.xml',
             'view/shipstaion_operation_detail.xml',
             'view/shipstation_delivery_carrier.xml',
             'view/shipstation_delivery_carrier_service.xml',
             'view/delivery_carrier.xml',
             'view/shipstation_delivery_carrier_package.xml',
             'view/stock_picking.xml',
             ],
    'images': [
        'static/description/odoo_shipstation.png',
    ],
    'demo': [],
    'installable': True,
    'auto_install': False,
    'application': True,
}
